import '../models/casino_game.dart';

/// Cover art + preview clips for casino tiles.
///
/// Mirrors `client/src/utils/preview.js` on the website: every game resolves
/// to a *theme*, and the theme decides both the cover (`assets/art/<theme>.jpg`)
/// and the looping demo clip (`assets/demos/slot-<theme>.mp4`). Table games use
/// the bespoke engine clip instead (`assets/demos/roulette.mp4`, …).
class GamePreviewAssets {
  GamePreviewAssets._();

  /// Theme nouns generated by the website's art tool — each has a cover and a
  /// slot clip of its own.
  static const List<String> themeNouns = [
    'feniks', 'zmaj', 'hram', 'rudnik', 'karavan', 'sedam', 'kotac', 'piramida',
    'vitez', 'grom', 'delfin', 'vulkan', 'safir', 'kompas', 'galeb', 'jelen',
    'maslina', 'sidro', 'lampion', 'kovceg', 'bubanj', 'kraljica', 'amfora',
    'otok', 'zvono', 'kljuc', 'krila', 'tigar', 'orao', 'val',
  ];

  /// Hand-picked theme per catalogue game so the clip matches the title's mood.
  static const Map<String, String> _themeById = {
    'vatreni_cup': 'grom',
    'psk_hot_40': 'sedam',
    'gates_of_olympus': 'hram',
    'sweet_bonanza': 'lampion',
    'big_bass_bonanza': 'delfin',
    'forge_of_olympus': 'vulkan',
    'fire_stampede': 'tigar',
    'wild_west_duels': 'karavan',
    'buffalo_blitz_live': 'jelen',
    'shining_crown': 'kraljica',
    'burning_hot': 'zvono',
    'age_of_gods': 'piramida',
    'super_hot_20': 'kljuc',
    'diamond_plus': 'safir',
    'book_of_ra': 'amfora',
    'lucky_ladys_charm': 'krila',
    'sizzling_hot': 'sedam',
    'sugar_rush': 'bubanj',
    'dolphins_pearl': 'delfin',
    'madame_destiny_mw': 'feniks',
    'great_rhino_mw': 'rudnik',
    'dog_house_mw': 'kotac',
  };

  static String themeFor(CasinoGame game) {
    switch (game.engine) {
      case GameEngine.roulette:
      case GameEngine.blackjack:
      case GameEngine.baccarat:
      case GameEngine.crash:
      case GameEngine.mines:
      case GameEngine.dice:
      case GameEngine.wheel:
        return game.engine.slug;
      case GameEngine.slot:
        break;
    }
    final mapped = _themeById[game.id];
    if (mapped != null) return mapped;
    final title = game.title.toLowerCase();
    for (final noun in themeNouns) {
      if (title.contains(noun)) return noun;
    }
    // stable fallback so the same game always gets the same art
    var h = 0;
    for (final c in game.id.codeUnits) {
      h = (h * 31 + c) & 0x7FFFFFFF;
    }
    return themeNouns[h % themeNouns.length];
  }

  /// Cover image asset path. Always resolves.
  static String artFor(CasinoGame game) => 'assets/art/${themeFor(game)}.jpg';

  /// Looping demo clip + poster for a game.
  static GamePreviewClip clipFor(CasinoGame game) {
    final theme = themeFor(game);
    final slug = game.isTableGame ? theme : 'slot-$theme';
    return GamePreviewClip(
      slug: slug,
      theme: theme,
      video: 'assets/demos/$slug.mp4',
      poster: 'assets/demos/$slug.jpg',
    );
  }
}

class GamePreviewClip {
  final String slug;
  final String theme;
  final String video;
  final String poster;

  const GamePreviewClip({
    required this.slug,
    required this.theme,
    required this.video,
    required this.poster,
  });
}
