import 'played_game_log.dart';
import 'placed_bet_ticket.dart';
import 'bet_slip_model.dart';

class DemoUserProfile {
  final String id;
  final String username;
  final String password;
  final String fullName;
  final String avatar;
  final String badge;
  final double startingBalance;
  final String tag;
  final String description;
  final List<PlayedGameLog> recentGames;
  final List<PlacedBetTicket> recentTickets;

  const DemoUserProfile({
    required this.id,
    required this.username,
    required this.password,
    required this.fullName,
    required this.avatar,
    required this.badge,
    required this.startingBalance,
    required this.tag,
    required this.description,
    this.recentGames = const [],
    this.recentTickets = const [],
  });

  static List<DemoUserProfile> get demoProfiles => [
    DemoUserProfile(
      id: 'vip_1',
      username: 'Marko_VIP',
      password: 'password123',
      fullName: 'Marko Horvat',
      avatar: '👑',
      badge: 'VIP Gold Tier',
      startingBalance: 5000.00,
      tag: 'HIGH ROLLER',
      description: 'VIP Gold Tier • High Stakes Sportsbook & VIP Blackjack',
      recentGames: [
        PlayedGameLog(
          id: 'marko_game_1',
          gameId: 'psk_blackjack',
          gameTitle: 'PSK VIP Blackjack',
          category: 'Table Games',
          provider: 'Playtech',
          gameIcon: '♠️',
          timestamp: DateTime.now().subtract(const Duration(minutes: 42)),
          stake: 500.00,
          winAmount: 1250.00,
          roundsPlayed: 5,
          summary: 'Won 1,250.00 € • Natural Blackjack & Double Down Win',
          detailedLogs: [
            'Hand #1: Dealt [K♠, 9♦] (19) vs Dealer [7♥, Q♣] (17) • Stand at 19 • Won +200.00 €',
            'Hand #2: Dealt [A♠, J♦] • NATURAL BLACKJACK! (3:2 payout) • Won +250.00 €',
            'Hand #3: Dealt [10♥, 6♠] (16) • Hit [5♦] (21!) • Dealer Busted [6♣, 8♦, K♠] (24) • Won +200.00 €',
            'Hand #4: Dealt [8♠, 8♣] • Split Hand 1 [8♠, Q♥] (18), Hand 2 [8♣, 9♦] (17) • Hand 1 Won, Hand 2 Push • Won +200.00 €',
            'Hand #5: Double Down on [5♥, 6♦] (11) • Received [10♠] (21!) • Dealer [K♦, 9♣] (19) • Won +400.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'marko_game_2',
          gameId: 'gates_of_olympus',
          gameTitle: 'Gates of Olympus',
          category: 'Slots',
          provider: 'Pragmatic Play',
          gameIcon: '⚡',
          timestamp: DateTime.now().subtract(const Duration(hours: 3, minutes: 15)),
          stake: 150.00,
          winAmount: 680.00,
          roundsPlayed: 30,
          summary: 'Won 680.00 € • 15 Free Spins with x85 Multiplier',
          detailedLogs: [
            'Spin #1-12: Base game tumbling cascades • 14 tumbling wins • +65.00 €',
            'Spin #13: 4x Zeus Scatters ⚡ hit! • 15 Free Spins Bonus triggered!',
            'Free Spin #4: Multiplier Orb x25 dropped on 12x Gem cluster! • +240.00 €',
            'Free Spin #11: Multiplier Orb x50 accumulated! Total multiplier x85 • +375.00 €',
            'Bonus Round Total: 615.00 € won • Session Finished',
          ],
        ),
        PlayedGameLog(
          id: 'marko_game_3',
          gameId: 'live_roulette_psk',
          gameTitle: 'Live Roulette PSK',
          category: 'Live Casino',
          provider: 'Playtech',
          gameIcon: '🎡',
          timestamp: DateTime.now().subtract(const Duration(hours: 18)),
          stake: 300.00,
          winAmount: 720.00,
          roundsPlayed: 6,
          summary: 'Won 720.00 € • Straight up #17 Black & Column Hit',
          detailedLogs: [
            'Round #1: Straight up #17 Black (50 €) & 1st Dozen (50 €) • Ball landed on #17 • WIN +1,800 € on straight up!',
            'Round #2: Red (100 €) • Ball landed on #26 Black • Loss -100.00 €',
            'Round #3: Columns 1 & 2 (100 €) • Ball landed on #4 • Win +50.00 €',
            'Round #4: High Numbers 19-36 (50 €) • Ball landed on #33 • Win +50.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'marko_game_4',
          gameId: 'vatreni_cup',
          gameTitle: 'Vatreni Cup',
          category: 'Slots',
          provider: 'Playtech',
          gameIcon: '🏆',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
          stake: 100.00,
          winAmount: 240.00,
          roundsPlayed: 25,
          summary: 'Won 240.00 € • Penalty Shootout Bonus Feature',
          detailedLogs: [
            'Spin #8: 3x Wild Football symbols on Reel 2, 3, 4 • Win +45.00 €',
            'Spin #19: Vatreni Cup Bonus feature triggered • Penalty shootout mini-game 4/5 scored • Win +195.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'marko_game_5',
          gameId: 'quantum_roulette',
          gameTitle: 'Quantum Roulette Live',
          category: 'Live Casino',
          provider: 'Playtech',
          gameIcon: '⚡',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 14)),
          stake: 250.00,
          winAmount: 850.00,
          roundsPlayed: 5,
          summary: 'Won 850.00 € • 100x Quantum Multiplier hit on #29',
          detailedLogs: [
            'Spin #2: 50 € Straight Up on #29 • Quantum Multiplier boosted to 100x • WIN +1,000.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'marko_game_6',
          gameId: 'sizzling_hot',
          gameTitle: 'Sizzling Hot Deluxe',
          category: 'Slots',
          provider: 'Novomatic',
          gameIcon: '🔥',
          timestamp: DateTime.now().subtract(const Duration(days: 2)),
          stake: 150.00,
          winAmount: 310.00,
          roundsPlayed: 20,
          summary: 'Won 310.00 € • 5x Watermelons & Flaming 7s',
          detailedLogs: [
            'Spin #7: 5x Watermelons on Payline 1 • Win +150.00 €',
            'Spin #16: 4x Flaming 7s on Payline 3 • Win +160.00 €',
          ],
        ),
      ],
      recentTickets: [
        PlacedBetTicket(
          id: 'HR-88421-2026',
          placedAt: DateTime.now().subtract(const Duration(minutes: 50)),
          stake: 500.00,
          totalOdds: 2.70,
          potentialWin: 1350.00,
          status: TicketStatus.inPlay,
          legs: const [
            PlacedBetLeg(
              selection: BetSelection(
                eventId: 'live_2',
                homeTeam: 'Real Madrid',
                awayTeam: 'Manchester City',
                league: 'UEFA Champions League',
                marketName: 'Match Winner',
                selectionLabel: '1',
                oddValue: 2.70,
                isLive: true,
              ),
              outcome: LegOutcome.winning,
              currentScore: '1–1',
              matchMinute: '41\'',
            ),
          ],
        ),
        PlacedBetTicket(
          id: 'HR-99214-2026',
          placedAt: DateTime.now().subtract(const Duration(hours: 1, minutes: 30)),
          stake: 1000.00,
          totalOdds: 1.48,
          potentialWin: 1480.00,
          status: TicketStatus.inPlay,
          legs: const [
            PlacedBetLeg(
              selection: BetSelection(
                eventId: 'live_bball_1',
                homeTeam: 'Denver Nuggets',
                awayTeam: 'Phoenix Suns',
                league: 'NBA',
                marketName: 'Moneyline',
                selectionLabel: '1',
                oddValue: 1.48,
                isLive: true,
              ),
              outcome: LegOutcome.winning,
              currentScore: '78–74',
              matchMinute: 'Q3',
            ),
          ],
        ),
        PlacedBetTicket(
          id: 'HR-71203-2026',
          placedAt: DateTime.now().subtract(const Duration(days: 1)),
          settledAt: DateTime.now().subtract(const Duration(hours: 22)),
          stake: 400.00,
          totalOdds: 2.09,
          potentialWin: 836.00,
          status: TicketStatus.won,
          legs: const [
            PlacedBetLeg(
              selection: BetSelection(
                eventId: 'live_1',
                homeTeam: 'Dinamo Zagreb',
                awayTeam: 'Hajduk Split',
                league: 'SuperSport HNL',
                marketName: 'Match Winner',
                selectionLabel: '1',
                oddValue: 1.35,
              ),
              outcome: LegOutcome.won,
              currentScore: '2–1',
            ),
            PlacedBetLeg(
              selection: BetSelection(
                eventId: 'live_4',
                homeTeam: 'Bayern Munich',
                awayTeam: 'Arsenal',
                league: 'UEFA Champions League',
                marketName: 'Match Winner',
                selectionLabel: '1',
                oddValue: 1.55,
              ),
              outcome: LegOutcome.won,
              currentScore: '1–0',
            ),
          ],
        ),
      ],
    ),
    DemoUserProfile(
      id: 'sports_1',
      username: 'Luka_HNL_Pro',
      password: 'password123',
      fullName: 'Luka Kovačić',
      avatar: '⚽',
      badge: 'Sportsbook Master',
      startingBalance: 350.00,
      tag: 'FOOTBALL PRO',
      description: 'SuperSport HNL & Champions League Specialist',
      recentGames: [
        PlayedGameLog(
          id: 'luka_game_1',
          gameId: 'vatreni_cup',
          gameTitle: 'Vatreni Cup',
          category: 'Slots',
          provider: 'Playtech',
          gameIcon: '⚽',
          timestamp: DateTime.now().subtract(const Duration(hours: 1, minutes: 20)),
          stake: 25.00,
          winAmount: 92.50,
          roundsPlayed: 20,
          summary: 'Won 92.50 € • Golden Trophy Scatters & 10 Free Spins',
          detailedLogs: [
            'Spin #1-5: Base game warmup • Stake 1.00 € per spin • Win +4.00 €',
            'Spin #9: 4x Dinamo jersey symbols on payline 3 • Win +28.50 €',
            'Spin #14: 3x 🏆 Golden Trophy Scatters triggered 10 Free Spins',
            'Free Spins Round: Total Win +60.00 € with Croatian stadium audio',
          ],
        ),
        PlayedGameLog(
          id: 'luka_game_2',
          gameId: 'european_roulette',
          gameTitle: 'European Roulette Pro',
          category: 'Table Games',
          provider: 'Playtech',
          gameIcon: '🎡',
          timestamp: DateTime.now().subtract(const Duration(hours: 5)),
          stake: 40.00,
          winAmount: 80.00,
          roundsPlayed: 8,
          summary: 'Won 80.00 € • Outside Bets Streak (Even/Odd/Red)',
          detailedLogs: [
            'Spin #1: Bet 10 € on Low (1-18) • Result: 9 Red • Win +20.00 €',
            'Spin #3: Bet 10 € on Even • Result: 14 Red • Win +20.00 €',
            'Spin #5: Bet 10 € on Black • Result: 11 Black • Win +20.00 €',
            'Spin #7: Bet 10 € on Red • Result: 22 Black • Loss -10.00 €',
            'Spin #8: Bet 10 € on Odd • Result: 7 Red • Win +20.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'luka_game_3',
          gameId: 'hnl_virtual_derby',
          gameTitle: 'SuperSport HNL Virtuals',
          category: 'Virtuals',
          provider: 'Playtech',
          gameIcon: '🎮',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 4)),
          stake: 30.00,
          winAmount: 75.00,
          roundsPlayed: 3,
          summary: 'Won 75.00 € • Dinamo vs Osijek & Hajduk vs Rijeka virtuals',
          detailedLogs: [
            'Virtual Match #1: Dinamo Zagreb vs Osijek • Bet: Over 2.5 (1.90) • Final: 3-1 • Won +28.50 €',
            'Virtual Match #2: Hajduk vs Rijeka • Bet: Both Teams to Score (1.85) • Final: 2-2 • Won +27.75 €',
            'Virtual Match #3: Lokomotiva vs Slaven • Bet: Home Win (2.05) • Final: 0-1 • Lost -10.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'luka_game_4',
          gameId: 'psk_hot_40',
          gameTitle: 'PSK HOT 40',
          category: 'Slots',
          provider: 'Fazi',
          gameIcon: '🎰',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 16)),
          stake: 50.00,
          winAmount: 115.00,
          roundsPlayed: 25,
          summary: 'Won 115.00 € • 40 Lines Flaming Sevens & Stars',
          detailedLogs: [
            'Spin #11: 4x Golden Bells • Win +35.00 €',
            'Spin #22: 5x Red Sevens on Line 17 • Win +80.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'luka_game_5',
          gameId: 'book_of_ra',
          gameTitle: 'Book of Ra Deluxe',
          category: 'Slots',
          provider: 'Novomatic',
          gameIcon: '📖',
          timestamp: DateTime.now().subtract(const Duration(days: 2)),
          stake: 35.00,
          winAmount: 78.00,
          roundsPlayed: 15,
          summary: 'Won 78.00 € • 3x Books Scatters & Explorer win',
          detailedLogs: [
            'Spin #8: 3x Books Scatters • 10 Free Spins • Win +65.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'luka_game_6',
          gameId: 'loto_italy_10e',
          gameTitle: 'Italy 10e Lotto 20/90',
          category: 'Lottery',
          provider: 'PSK Lotto',
          gameIcon: '🎱',
          timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 6)),
          stake: 20.00,
          winAmount: 65.00,
          roundsPlayed: 3,
          summary: 'Won 65.00 € • 4/5 Numbers Matched [7, 14, 28, 56]',
          detailedLogs: [
            'Draw #1284: Matched 4 numbers • Payout multiplier 3.25x • Won +65.00 €',
          ],
        ),
      ],
      recentTickets: [
        PlacedBetTicket(
          id: 'HR-54129-2026',
          placedAt: DateTime.now().subtract(const Duration(minutes: 35)),
          stake: 50.00,
          totalOdds: 1.35,
          potentialWin: 67.50,
          status: TicketStatus.inPlay,
          legs: const [
            PlacedBetLeg(
              selection: BetSelection(
                eventId: 'live_1',
                homeTeam: 'Dinamo Zagreb',
                awayTeam: 'Hajduk Split',
                league: 'SuperSport HNL',
                marketName: 'Match Winner',
                selectionLabel: '1',
                oddValue: 1.35,
                isLive: true,
              ),
              outcome: LegOutcome.winning,
              currentScore: '2–1',
              matchMinute: '67\'',
            ),
          ],
        ),
        PlacedBetTicket(
          id: 'HR-63201-2026',
          placedAt: DateTime.now().subtract(const Duration(hours: 2, minutes: 15)),
          settledAt: DateTime.now().subtract(const Duration(minutes: 10)),
          stake: 40.00,
          totalOdds: 1.45,
          potentialWin: 58.00,
          status: TicketStatus.won,
          legs: const [
            PlacedBetLeg(
              selection: BetSelection(
                eventId: 'live_2',
                homeTeam: 'Real Madrid',
                awayTeam: 'Manchester City',
                league: 'UEFA Champions League',
                marketName: 'Both Teams to Score',
                selectionLabel: 'Yes',
                oddValue: 1.45,
                isLive: true,
              ),
              outcome: LegOutcome.won,
              currentScore: '1–1',
            ),
          ],
        ),
        PlacedBetTicket(
          id: 'HR-39014-2026',
          placedAt: DateTime.now().subtract(const Duration(hours: 4)),
          stake: 25.00,
          totalOdds: 3.98,
          potentialWin: 99.50,
          status: TicketStatus.inPlay,
          legs: const [
            PlacedBetLeg(
              selection: BetSelection(
                eventId: 'live_1',
                homeTeam: 'Dinamo Zagreb',
                awayTeam: 'Hajduk Split',
                league: 'SuperSport HNL',
                marketName: 'Match Winner',
                selectionLabel: '1',
                oddValue: 1.35,
                isLive: true,
              ),
              outcome: LegOutcome.winning,
              currentScore: '2–1',
            ),
            PlacedBetLeg(
              selection: BetSelection(
                eventId: 'live_5',
                homeTeam: 'Inter Milan',
                awayTeam: 'Juventus',
                league: 'Serie A',
                marketName: 'Match Winner',
                selectionLabel: '1',
                oddValue: 1.90,
                isLive: true,
              ),
              outcome: LegOutcome.pending,
              currentScore: '0–0',
            ),
            PlacedBetLeg(
              selection: BetSelection(
                eventId: 'live_4',
                homeTeam: 'Bayern Munich',
                awayTeam: 'Arsenal',
                league: 'UEFA Champions League',
                marketName: 'Match Winner',
                selectionLabel: '1',
                oddValue: 1.55,
                isLive: true,
              ),
              outcome: LegOutcome.winning,
              currentScore: '1–0',
            ),
          ],
        ),
      ],
    ),
    DemoUserProfile(
      id: 'casino_1',
      username: 'Ana_SpinQueen',
      password: 'password123',
      fullName: 'Ana Marić',
      avatar: '🎰',
      badge: 'Casino VIP',
      startingBalance: 1500.00,
      tag: 'CASINO ELITE',
      description: 'Slots & European Roulette Enthusiast',
      recentGames: [
        PlayedGameLog(
          id: 'ana_game_1',
          gameId: 'shining_crown',
          gameTitle: 'Shining Crown',
          category: 'Slots',
          provider: 'EGT Digital',
          gameIcon: '👑',
          timestamp: DateTime.now().subtract(const Duration(minutes: 30)),
          stake: 120.00,
          winAmount: 540.00,
          roundsPlayed: 40,
          summary: 'Won 540.00 € • Expanding Wild Crown & 5x Sevens',
          detailedLogs: [
            'Spin #4: Expanding Wild Crown 👑 on Reel 2, 3, 4! Full screen fruits! • Won +320.00 €',
            'Spin #12: 3x Star Scatters on Reel 1, 3, 5 • Won +60.00 €',
            'Spin #24: 5x Red Sevens 7️⃣ on Payline 2! Mega Win! • Won +160.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'ana_game_2',
          gameId: 'sweet_bonanza',
          gameTitle: 'Sweet Bonanza',
          category: 'Slots',
          provider: 'Pragmatic Play',
          gameIcon: '🍭',
          timestamp: DateTime.now().subtract(const Duration(hours: 4)),
          stake: 100.00,
          winAmount: 385.00,
          roundsPlayed: 25,
          summary: 'Won 385.00 € • 10 Free Spins with 25x Sugar Bombs',
          detailedLogs: [
            'Spin #7: 4x Lollipops 🍭 triggered Free Spins Feature (10 Free Spins)',
            'Free Spin #3: Tumbling win with 12x Candy Heart • Bomb multiplier 15x • Won +145.00 €',
            'Free Spin #8: Sugar Bomb 25x combined with banana tumble • Won +190.00 €',
            'Free Spins Total: +335.00 € credited to balance',
          ],
        ),
        PlayedGameLog(
          id: 'ana_game_3',
          gameId: 'european_roulette',
          gameTitle: 'European Roulette Pro',
          category: 'Table Games',
          provider: 'Playtech',
          gameIcon: '🎡',
          timestamp: DateTime.now().subtract(const Duration(hours: 19)),
          stake: 150.00,
          winAmount: 320.00,
          roundsPlayed: 10,
          summary: 'Won 320.00 € • 2nd Dozen & Split [17/20] Wins',
          detailedLogs: [
            'Spin #1: 25 € on Black • Landed: 29 Black • Win +50.00 €',
            'Spin #3: 50 € on 2nd Dozen (13-24) • Landed: 20 Black • Win +150.00 €',
            'Spin #6: 25 € on Red • Landed: 1 Red • Win +50.00 €',
            'Spin #8: 20 € Split [17/20] • Landed: 17 Black • Win +70.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'ana_game_4',
          gameId: 'book_of_dead',
          gameTitle: 'Book of Dead',
          category: 'Slots',
          provider: 'Playtech',
          gameIcon: '📖',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 8)),
          stake: 80.00,
          winAmount: 165.00,
          roundsPlayed: 20,
          summary: 'Won 165.00 € • Expanding Rich Wilde Symbol Feature',
          detailedLogs: [
            'Spin #14: 3x Golden Books triggered 10 Free Spins',
            'Free Spin #6: Expanding Rich Wilde covered 4 reels • Big Win +125.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'ana_game_5',
          gameId: 'sugar_rush',
          gameTitle: 'Sugar Rush 1000',
          category: 'Slots',
          provider: 'Pragmatic Play',
          gameIcon: '🍬',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 22)),
          stake: 75.00,
          winAmount: 260.00,
          roundsPlayed: 30,
          summary: 'Won 260.00 € • 128x Multiplier Spot Cluster Pays',
          detailedLogs: [
            'Spin #18: Gummy Bears cluster ignited spot to 128x • Mega Win +210.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'ana_game_6',
          gameId: 'super_hot_20',
          gameTitle: '20 Super Hot',
          category: 'Slots',
          provider: 'EGT Digital',
          gameIcon: '🔥',
          timestamp: DateTime.now().subtract(const Duration(days: 2)),
          stake: 60.00,
          winAmount: 145.00,
          roundsPlayed: 20,
          summary: 'Won 145.00 € • 5x Grapes & Star Scatters',
          detailedLogs: [
            'Spin #9: Full line Grapes with 7 Wild • Win +95.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'ana_game_7',
          gameId: 'big_bass_bonanza',
          gameTitle: 'Big Bass Bonanza',
          category: 'Slots',
          provider: 'Pragmatic Play',
          gameIcon: '🎣',
          timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 10)),
          stake: 90.00,
          winAmount: 198.00,
          roundsPlayed: 35,
          summary: 'Won 198.00 € • Fisherman collected 3x Big Fish',
          detailedLogs: [
            'Free Spin #5: Fisherman 🎣 collected 50.00 € and 25.00 € bass • Win +75.00 €',
          ],
        ),
      ],
      recentTickets: [
        PlacedBetTicket(
          id: 'HR-42109-2026',
          placedAt: DateTime.now().subtract(const Duration(hours: 1)),
          stake: 50.00,
          totalOdds: 1.62,
          potentialWin: 81.00,
          status: TicketStatus.inPlay,
          legs: const [
            PlacedBetLeg(
              selection: BetSelection(
                eventId: 'live_ten_2',
                homeTeam: 'Carlos Alcaraz',
                awayTeam: 'Jannik Sinner',
                league: 'ATP Masters Live',
                marketName: 'Match Winner',
                selectionLabel: '1',
                oddValue: 1.62,
                isLive: true,
              ),
              outcome: LegOutcome.winning,
              currentScore: '1–1 (Set 3)',
            ),
          ],
        ),
        PlacedBetTicket(
          id: 'HR-38291-2026',
          placedAt: DateTime.now().subtract(const Duration(days: 1)),
          settledAt: DateTime.now().subtract(const Duration(hours: 18)),
          stake: 30.00,
          totalOdds: 1.70,
          potentialWin: 51.00,
          status: TicketStatus.won,
          legs: const [
            PlacedBetLeg(
              selection: BetSelection(
                eventId: 'live_4',
                homeTeam: 'Bayern Munich',
                awayTeam: 'Arsenal',
                league: 'UEFA Champions League',
                marketName: 'Total Goals',
                selectionLabel: 'Over 2.5',
                oddValue: 1.70,
              ),
              outcome: LegOutcome.won,
              currentScore: '1–0',
            ),
          ],
        ),
      ],
    ),
    DemoUserProfile(
      id: 'casual_1',
      username: 'Casual_Matej',
      password: 'password123',
      fullName: 'Matej Babić',
      avatar: '🎯',
      badge: 'Casual Player',
      startingBalance: 75.00,
      tag: 'WEEKEND WARRIOR',
      description: 'Micro-stakes Casino Slots & Derby Multi-bets',
      recentGames: [
        PlayedGameLog(
          id: 'matej_game_1',
          gameId: 'vatreni_cup',
          gameTitle: 'Vatreni Cup',
          category: 'Slots',
          provider: 'Playtech',
          gameIcon: '⚽',
          timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 10)),
          stake: 6.00,
          winAmount: 24.50,
          roundsPlayed: 12,
          summary: 'Won 24.50 € • 4x Dinamo Shields on 0.50 € Bet',
          detailedLogs: [
            'Spin #3: Bet 0.50 € • 3x Croatian Boots • Win +1.50 €',
            'Spin #7: Bet 0.50 € • 3x Stadium Scatters • Win +3.00 €',
            'Spin #12: Bet 0.50 € • 4x Dinamo Shields • Win +20.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'matej_game_2',
          gameId: 'psk_blackjack',
          gameTitle: 'PSK VIP Blackjack',
          category: 'Table Games',
          provider: 'Playtech',
          gameIcon: '♠️',
          timestamp: DateTime.now().subtract(const Duration(hours: 6)),
          stake: 15.00,
          winAmount: 30.00,
          roundsPlayed: 3,
          summary: 'Won 30.00 € • 2 Hands won against Dealer bust',
          detailedLogs: [
            'Hand #1: Bet 5.00 € • Dealt [10♣, 9♠] (19) vs Dealer [8♦, 10♥] (18) • Stand • Win +10.00 €',
            'Hand #2: Bet 5.00 € • Dealt [A♦, 8♠] (Soft 19) vs Dealer [9♣, 7♥] (16 - Hit 8 - 24 BUST) • Win +10.00 €',
            'Hand #3: Bet 5.00 € • Dealt [Q♠, J♦] (20) vs Dealer [K♥, 10♠] (20) • Push 5.00 € returned',
          ],
        ),
        PlayedGameLog(
          id: 'matej_game_3',
          gameId: 'burning_hot',
          gameTitle: 'Burning Hot',
          category: 'Slots',
          provider: 'EGT Digital',
          gameIcon: '🔥',
          timestamp: DateTime.now().subtract(const Duration(days: 1)),
          stake: 8.00,
          winAmount: 18.20,
          roundsPlayed: 16,
          summary: 'Won 18.20 € • 4-Leaf Clover Wild & Cherries',
          detailedLogs: [
            'Spin #5: 3x Cherries on Payline 1 • Win +1.80 €',
            'Spin #11: 4-Leaf Clover Wild on Reel 2 • Win +16.40 €',
          ],
        ),
        PlayedGameLog(
          id: 'matej_game_4',
          gameId: 'lucky_ladys_charm',
          gameTitle: 'Lucky Lady\'s Charm',
          category: 'Slots',
          provider: 'Novomatic',
          gameIcon: '🐞',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 12)),
          stake: 5.00,
          winAmount: 14.50,
          roundsPlayed: 10,
          summary: 'Won 14.50 € • Lady Luck Wilds on 0.50 € Bet',
          detailedLogs: [
            'Spin #4: 2x Lady Luck Wilds • Win +12.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'matej_game_5',
          gameId: 'dolphins_pearl',
          gameTitle: 'Dolphin\'s Pearl Deluxe',
          category: 'Slots',
          provider: 'Novomatic',
          gameIcon: '🐬',
          timestamp: DateTime.now().subtract(const Duration(days: 2)),
          stake: 4.00,
          winAmount: 11.20,
          roundsPlayed: 8,
          summary: 'Won 11.20 € • Pearl Scatters & Seahorse Win',
          detailedLogs: [
            'Spin #6: 3x Seahorse symbols • Win +9.00 €',
          ],
        ),
        PlayedGameLog(
          id: 'matej_game_6',
          gameId: 'loto_greek_kino',
          gameTitle: 'Greek Kino 20/80',
          category: 'Lottery',
          provider: 'PSK Lotto',
          gameIcon: '🎱',
          timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 8)),
          stake: 5.00,
          winAmount: 25.00,
          roundsPlayed: 2,
          summary: 'Won 25.00 € • Matched 3/3 Numbers [3, 19, 42]',
          detailedLogs: [
            'Draw #5419: Matched all 3 numbers • Payout 5x • Won +25.00 €',
          ],
        ),
      ],
      recentTickets: [
        PlacedBetTicket(
          id: 'HR-19042-2026',
          placedAt: DateTime.now().subtract(const Duration(minutes: 40)),
          stake: 10.00,
          totalOdds: 1.35,
          potentialWin: 13.50,
          status: TicketStatus.inPlay,
          legs: const [
            PlacedBetLeg(
              selection: BetSelection(
                eventId: 'live_1',
                homeTeam: 'Dinamo Zagreb',
                awayTeam: 'Hajduk Split',
                league: 'SuperSport HNL',
                marketName: 'Match Winner',
                selectionLabel: '1',
                oddValue: 1.35,
                isLive: true,
              ),
              outcome: LegOutcome.winning,
              currentScore: '2–1',
              matchMinute: '67\'',
            ),
          ],
        ),
        PlacedBetTicket(
          id: 'HR-20815-2026',
          placedAt: DateTime.now().subtract(const Duration(days: 1)),
          settledAt: DateTime.now().subtract(const Duration(hours: 20)),
          stake: 15.00,
          totalOdds: 1.38,
          potentialWin: 20.70,
          status: TicketStatus.won,
          legs: const [
            PlacedBetLeg(
              selection: BetSelection(
                eventId: 'live_esp_1',
                homeTeam: 'Natus Vincere (NAVI)',
                awayTeam: 'FaZe Clan',
                league: 'CS2 PGL Major',
                marketName: 'Map Winner',
                selectionLabel: '1',
                oddValue: 1.38,
              ),
              outcome: LegOutcome.won,
              currentScore: '1–0',
            ),
          ],
        ),
      ],
    ),
  ];
}
